service: serverless-test-api # NOTE: update this with your service name



provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment: 
    NOTES_TABLE: ${self:service}-${opt:stage, self:provider.stage}



functions:
  hello:
    handler: handler.hello
